# Generated by Django 4.0.1 on 2022-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='complete', max_length=250),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(blank=True, default='2022-01-21', null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(blank=True, default='2022-01-21', null=True),
        ),
    ]
